-- zad1
SELECT LAST_NAME || ' ' || SALARY AS "wynagrodzenie"
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (20, 50)
  AND SALARY BETWEEN 2000 AND 7000
ORDER BY LAST_NAME;
-- zad2
SELECT HIRE_DATE, LAST_NAME, :wybrana_kolumna
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
  AND EXTRACT(YEAR FROM HIRE_DATE) = 2005
ORDER BY :wybrana_kolumna;
-- zad3
SELECT FIRST_NAME || ' ' || LAST_NAME AS "Imię i Nazwisko", 
       SALARY, 
       PHONE_NUMBER
FROM EMPLOYEES
WHERE LAST_NAME LIKE '__e%' 
  AND FIRST_NAME LIKE '%' || :czesc_imienia || '%'
ORDER BY 1 DESC, 3 ASC;
-- zad4
SELECT 
    FIRST_NAME, 
    LAST_NAME, 
    ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS LICZBA_MIESIECY,
    CASE 
        WHEN MONTHS_BETWEEN(SYSDATE, HIRE_DATE) < 150 THEN SALARY * 0.10
        WHEN MONTHS_BETWEEN(SYSDATE, HIRE_DATE) >= 150 AND MONTHS_BETWEEN(SYSDATE, HIRE_DATE) < 200 THEN SALARY * 0.20
        ELSE SALARY * 0.30
    END AS "wysokość_dodatku"
FROM EMPLOYEES
ORDER BY LICZBA_MIESIECY;
-- zad5
SELECT 
    j.FIRST_NAME AS "Imię Pracownika", 
    j.LAST_NAME AS "Nazwisko Pracownika",
    e.FIRST_NAME AS "Imię Wspólpracownika", 
    e.LAST_NAME AS "Nazwisko Wspólpracownika"
FROM EMPLOYEES j
JOIN EMPLOYEES e ON j.DEPARTMENT_ID = e.DEPARTMENT_ID
WHERE j.FIRST_NAME = 'Jennifer'
  AND (j.EMPLOYEE_ID <> e.EMPLOYEE_ID);
-- zad6
SELECT 
    DEPARTMENT_ID, 
    SUM(SALARY) AS "Suma zarobków", 
    ROUND(AVG(SALARY)) AS "Średnia zarobków"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MIN(SALARY) > 5000;
-- zad7
SELECT 
    e.LAST_NAME, 
    e.DEPARTMENT_ID, 
    d.DEPARTMENT_NAME, 
    e.JOB_ID
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID
WHERE l.CITY = 'Toronto';
-- zad8 
SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_ID NOT IN (
    SELECT DEPARTMENT_ID 
    FROM EMPLOYEES 
    WHERE DEPARTMENT_ID IS NOT NULL
);
-- zad9
SELECT 
    e.FIRST_NAME, 
    e.LAST_NAME, 
    e.JOB_ID, 
    d.DEPARTMENT_NAME, 
    e.SALARY, 
    jg.GRADE
FROM EMPLOYEES e
LEFT JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN JOB_GRADES jg ON e.SALARY BETWEEN jg.MIN_SALARY AND jg.MAX_SALARY;
-- zad10
SELECT 
    FIRST_NAME, 
    LAST_NAME, 
    SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES)
ORDER BY SALARY DESC;
-- zad11
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DISTINCT DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE LOWER(LAST_NAME) LIKE '%u%'
);