-- cw1
-- zad1
CREATE OR REPLACE FUNCTION f_nazwa_pracy(p_job_id IN VARCHAR2) RETURN VARCHAR2 IS
    v_title jobs.job_title%TYPE;
BEGIN
    SELECT job_title INTO v_title FROM jobs WHERE job_id = p_job_id;
    RETURN v_title;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Błąd: Praca o podanym ID nie istnieje';
END f_nazwa_pracy;
/
-- zad2
CREATE OR REPLACE FUNCTION f_roczne_zarobki(p_emp_id IN NUMBER) RETURN NUMBER IS
    v_salary employees.salary%TYPE;
    v_comm employees.commission_pct%TYPE;
BEGIN
    SELECT salary, NVL(commission_pct, 0) INTO v_salary, v_comm 
    FROM employees WHERE employee_id = p_emp_id;
    RETURN (v_salary * 12) + (v_salary * v_comm);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END f_roczne_zarobki;
/
-- zad3
CREATE OR REPLACE FUNCTION f_formatuj_telefon(p_telefon IN VARCHAR2) RETURN VARCHAR2 IS
BEGIN
    IF LENGTH(p_telefon) >= 3 THEN
        RETURN '(' || SUBSTR(p_telefon, 1, 3) || ')' || SUBSTR(p_telefon, 4);
    ELSE
        RETURN p_telefon;
    END IF;
END f_formatuj_telefon;
/
-- zad4
CREATE OR REPLACE FUNCTION f_dziwna_wielkosc(p_tekst IN VARCHAR2) RETURN VARCHAR2 IS
    v_dlugosc NUMBER := LENGTH(p_tekst);
BEGIN
    IF p_tekst IS NULL THEN RETURN NULL; END IF;
    IF v_dlugosc = 1 THEN RETURN UPPER(p_tekst); END IF;
    
    RETURN UPPER(SUBSTR(p_tekst, 1, 1)) || 
           LOWER(SUBSTR(p_tekst, 2, v_dlugosc - 2)) || 
           UPPER(SUBSTR(p_tekst, -1));
END f_dziwna_wielkosc;
/
-- zad5
CREATE OR REPLACE FUNCTION f_pesel_na_date(p_pesel IN VARCHAR2) RETURN DATE IS
    v_rok VARCHAR2(4);
    v_miesiac VARCHAR2(2);
    v_dzien VARCHAR2(2);
    v_miesiac_num NUMBER;
BEGIN
    IF LENGTH(p_pesel) != 11 THEN RETURN NULL; END IF;
    
    v_rok := SUBSTR(p_pesel, 1, 2);
    v_miesiac_num := TO_NUMBER(SUBSTR(p_pesel, 3, 2));
    v_dzien := SUBSTR(p_pesel, 5, 2);
    
    IF v_miesiac_num > 20 THEN
        v_rok := '20' || v_rok;
        v_miesiac := TO_CHAR(v_miesiac_num - 20, 'FM00');
    ELSE
        v_rok := '19' || v_rok;
        v_miesiac := TO_CHAR(v_miesiac_num, 'FM00');
    END IF;
    
    RETURN TO_DATE(v_rok || '-' || v_miesiac || '-' || v_dzien, 'YYYY-MM-DD');
END f_pesel_na_date;
/
-- zad6
CREATE OR REPLACE FUNCTION f_statystyki_kraju(
    p_kraj IN VARCHAR2,
    p_liczba_prac OUT NUMBER,
    p_liczba_dep OUT NUMBER
) RETURN BOOLEAN IS
    v_country_id countries.country_id%TYPE;
BEGIN
    SELECT country_id INTO v_country_id FROM countries WHERE UPPER(country_name) = UPPER(p_kraj);
    SELECT COUNT(DISTINCT d.department_id), COUNT(e.employee_id)
    INTO p_liczba_dep, p_liczba_prac
    FROM locations l
    LEFT JOIN departments d ON l.location_id = d.location_id
    LEFT JOIN employees e ON d.department_id = e.department_id
    WHERE l.country_id = v_country_id;
    
    RETURN TRUE;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Kraj o podanej nazwie nie istnieje w bazie.');
END f_statystyki_kraju;
/
-- cw2
-- zad1
CREATE TABLE archiwum_departamentow (
    id NUMBER,
    nazwa VARCHAR2(50),
    data_zamkniecia DATE,
    ostatni_manager VARCHAR2(100)
);
CREATE OR REPLACE TRIGGER trg_archiwum_dep
BEFORE DELETE ON departments
FOR EACH ROW
DECLARE
    v_manager_name VARCHAR2(100) := 'Brak';
BEGIN
    IF :OLD.manager_id IS NOT NULL THEN
        SELECT first_name || ' ' || last_name INTO v_manager_name 
        FROM employees WHERE employee_id = :OLD.manager_id;
    END IF;
    
    INSERT INTO archiwum_departamentow (id, nazwa, data_zamkniecia, ostatni_manager)
    VALUES (:OLD.department_id, :OLD.department_name, SYSDATE, v_manager_name);
END;
/
-- zad2
CREATE TABLE zlodziej (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uzytkownik VARCHAR2(50),
    czas_zmiany DATE
);
CREATE OR REPLACE TRIGGER trg_widelek_pensji
BEFORE INSERT OR UPDATE OF salary ON employees
FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION; 
BEGIN
    IF :NEW.salary < 2000 OR :NEW.salary > 26000 THEN
        INSERT INTO zlodziej (uzytkownik, czas_zmiany) VALUES (USER, SYSDATE);
        COMMIT;
        RAISE_APPLICATION_ERROR(-20002, 'Niedozwolone wynagrodzenie! Akcja zalogowana.');
    END IF;
END;
/
-- zad3
CREATE SEQUENCE seq_emp_auto_inc START WITH 1000 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_emp_auto_inc
BEFORE INSERT ON employees
FOR EACH ROW
BEGIN
    IF :NEW.employee_id IS NULL THEN
        :NEW.employee_id := seq_emp_auto_inc.NEXTVAL;
    END IF;
END;
/
-- zad4
CREATE OR REPLACE TRIGGER trg_zakaz_job_grades
BEFORE INSERT OR UPDATE OR DELETE ON JOB_GRADES
BEGIN
    RAISE_APPLICATION_ERROR(-20003, 'Wszelkie modyfikacje w tabeli JOB_GRADES są zabronione.');
END;
/
-- zad5
CREATE OR REPLACE TRIGGER trg_ochrona_salary_jobs
BEFORE UPDATE OF min_salary, max_salary ON jobs
FOR EACH ROW
BEGIN
    :NEW.min_salary := :OLD.min_salary;
    :NEW.max_salary := :OLD.max_salary;
END;
/
-- cw3
-- zad1
CREATE OR REPLACE PACKAGE pkg_narzedzia_hr IS
    FUNCTION f_nazwa_pracy(p_job_id VARCHAR2) RETURN VARCHAR2;
    FUNCTION f_formatuj_telefon(p_telefon VARCHAR2) RETURN VARCHAR2;
    FUNCTION f_dziwna_wielkosc(p_tekst VARCHAR2) RETURN VARCHAR2;
END pkg_narzedzia_hr;
/
CREATE OR REPLACE PACKAGE BODY pkg_narzedzia_hr IS

    FUNCTION f_nazwa_pracy(p_job_id VARCHAR2) RETURN VARCHAR2 IS
        v_title jobs.job_title%TYPE;
    BEGIN
        SELECT job_title INTO v_title FROM jobs WHERE job_id = p_job_id;
        RETURN v_title;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RETURN 'Brak';
    END;

    FUNCTION f_formatuj_telefon(p_telefon VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        IF LENGTH(p_telefon) >= 3 THEN
            RETURN '(' || SUBSTR(p_telefon, 1, 3) || ')' || SUBSTR(p_telefon, 4);
        ELSE
            RETURN p_telefon;
        END IF;
    END;

    FUNCTION f_dziwna_wielkosc(p_tekst VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        IF p_tekst IS NULL THEN RETURN NULL; END IF;
        IF LENGTH(p_tekst) = 1 THEN RETURN UPPER(p_tekst); END IF;
        RETURN UPPER(SUBSTR(p_tekst, 1, 1)) || 
               LOWER(SUBSTR(p_tekst, 2, LENGTH(p_tekst) - 2)) || 
               UPPER(SUBSTR(p_tekst, -1));
    END;
END pkg_narzedzia_hr;
/
-- zad2
CREATE OR REPLACE PACKAGE pkg_regions_crud IS
    PROCEDURE dodaj_region(p_id NUMBER, p_nazwa VARCHAR2);
    PROCEDURE aktualizuj_region(p_id NUMBER, p_nowa_nazwa VARCHAR2);
    PROCEDURE usun_region(p_id NUMBER);
    FUNCTION pobierz_nazwe_regionu(p_id NUMBER) RETURN VARCHAR2;
END pkg_regions_crud;
/
CREATE OR REPLACE PACKAGE BODY pkg_regions_crud IS
    PROCEDURE dodaj_region(p_id NUMBER, p_nazwa VARCHAR2) IS
    BEGIN
        INSERT INTO regions (region_id, region_name) VALUES (p_id, p_nazwa);
        COMMIT;
    END dodaj_region;
    PROCEDURE aktualizuj_region(p_id NUMBER, p_nowa_nazwa VARCHAR2) IS
    BEGIN
        UPDATE regions SET region_name = p_nowa_nazwa WHERE region_id = p_id;
        COMMIT;
    END aktualizuj_region;
    PROCEDURE usun_region(p_id NUMBER) IS
    BEGIN
        DELETE FROM regions WHERE region_id = p_id;
        COMMIT;
    END usun_region;
    FUNCTION pobierz_nazwe_regionu(p_id NUMBER) RETURN VARCHAR2 IS
        v_nazwa regions.region_name%TYPE;
    BEGIN
        SELECT region_name INTO v_nazwa FROM regions WHERE region_id = p_id;
        RETURN v_nazwa;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RETURN 'Region nie istnieje';
    END pobierz_nazwe_regionu;
END pkg_regions_crud;
/